title: "Yanxin Zhang"
name: "Yanxin Zhang"
description: "CS @ UW–Madison | ML for Systems, LLM Quantization, Diffusion Models"
locale: "en-US"

url: "https://yanxinzhangcs.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

author:
  name: "Yanxin Zhang"
  avatar: "/images/IMG_4369.jpg"  # 放在 /images/avatar.jpg
  bio: "Undergraduate @ UW–Madison. Research: ML for Systems, LLM Inference"
  location: "United States"
  email: "yzhang2879@wisc.edu"
  github: "https://github.com/yanxinzhangcs"
  googlescholar: "https://scholar.google.com/citations?user=n4T_jywAAAAJ&hl=en&authuser=1"
  linkedin: "https://www.linkedin.com/in/yanxin-zhang-b87b67312/"  

collections:
  publications:
    output: true
    permalink: /publications/:title/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

include: ["_pages"]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache 

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/